export enum ExceptionCode {
  // Authentication
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_MFA_REQUIRED = 'AUTH_MFA_REQUIRED',
  AUTH_MFA_INVALID = 'AUTH_MFA_INVALID',

  // Authorization
  AUTHZ_PERMISSION_DENIED = 'AUTHZ_PERMISSION_DENIED',
  AUTHZ_ROLE_REQUIRED = 'AUTHZ_ROLE_REQUIRED',
  AUTHZ_RESOURCE_ACCESS_DENIED = 'AUTHZ_RESOURCE_ACCESS_DENIED',
  AUTHZ_TENANT_ACCESS_DENIED = 'AUTHZ_TENANT_ACCESS_DENIED',
  AUTHZ_ORGANIZATION_ACCESS_DENIED = 'AUTHZ_ORGANIZATION_ACCESS_DENIED',

  // Resource - Generic
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  RESOURCE_GONE = 'RESOURCE_GONE',
  RESOURCE_LOCKED = 'RESOURCE_LOCKED',

  // Resource - Specific
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  JOB_NOT_FOUND = 'JOB_NOT_FOUND',
  JOB_EXPIRED = 'JOB_EXPIRED',
  JOB_CLOSED = 'JOB_CLOSED',
  APPLICATION_NOT_FOUND = 'APPLICATION_NOT_FOUND',
  APPLICATION_ALREADY_EXISTS = 'APPLICATION_ALREADY_EXISTS',
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',

  // Validation
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  VALIDATION_FIELD_REQUIRED = 'VALIDATION_FIELD_REQUIRED',
  VALIDATION_FIELD_INVALID = 'VALIDATION_FIELD_INVALID',
  VALIDATION_FIELD_TOO_SHORT = 'VALIDATION_FIELD_TOO_SHORT',
  VALIDATION_FIELD_TOO_LONG = 'VALIDATION_FIELD_TOO_LONG',
  VALIDATION_FIELD_FORMAT = 'VALIDATION_FIELD_FORMAT',
  VALIDATION_EMAIL_INVALID = 'VALIDATION_EMAIL_INVALID',
  VALIDATION_PHONE_INVALID = 'VALIDATION_PHONE_INVALID',
  VALIDATION_URL_INVALID = 'VALIDATION_URL_INVALID',
  VALIDATION_DATE_INVALID = 'VALIDATION_DATE_INVALID',
  VALIDATION_NUMBER_INVALID = 'VALIDATION_NUMBER_INVALID',
  VALIDATION_ENUM_INVALID = 'VALIDATION_ENUM_INVALID',
  VALIDATION_ARRAY_INVALID = 'VALIDATION_ARRAY_INVALID',
  VALIDATION_PASSWORD_WEAK = 'VALIDATION_PASSWORD_WEAK',
  VALIDATION_PASSWORDS_MISMATCH = 'VALIDATION_PASSWORDS_MISMATCH',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  RATE_LIMIT_TOO_MANY_REQUESTS = 'RATE_LIMIT_TOO_MANY_REQUESTS',
  RATE_LIMIT_QUOTA_EXCEEDED = 'RATE_LIMIT_QUOTA_EXCEEDED',

  // Payment
  PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_DECLINED = 'PAYMENT_DECLINED',
  PAYMENT_INSUFFICIENT_FUNDS = 'PAYMENT_INSUFFICIENT_FUNDS',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_REQUIRED = 'SUBSCRIPTION_REQUIRED',

  // File/Upload
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED = 'FILE_TYPE_NOT_ALLOWED',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  FILE_CORRUPTED = 'FILE_CORRUPTED',

  // External Services
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  EXTERNAL_SERVICE_TIMEOUT = 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_SERVICE_UNAVAILABLE = 'EXTERNAL_SERVICE_UNAVAILABLE',

  // Internal
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INTERNAL_DATABASE_ERROR = 'INTERNAL_DATABASE_ERROR',
  INTERNAL_CONFIGURATION_ERROR = 'INTERNAL_CONFIGURATION_ERROR',
  MAINTENANCE_MODE = 'MAINTENANCE_MODE',
}
